user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;
  # Redirect all unsecured port 80 traffic to the secure port 443.
  server {
    listen 0.0.0.0:80;
    return 301 https://$host$request_uri;
  }
  server {
    listen      0.0.0.0:443 ssl;
    #ssl_certificate /etc/ssl/certs/linuxsimba.crt;
    #ssl_certificate_key /etc/ssl/private/linuxsimba.key;

    ssl_certificate /etc/letsencrypt/live/[yourdomain]/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/[yourdomain]/privkey.pem;

    # default settings for Nginx 1.10.2. Just mentioning it for 
    # educational purposes. Older versions of Nginx have different cipher 
    # protocol settings.
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    location / {
        proxy_read_timeout 120;
        # Using docker to house jekyll container and nginx container
        # linuxsimba-blog is the docker network name for the jekyll container
        # on a bare-metal host proxy_pass will probably be http://localhost:4000
        proxy_pass  http://localhost:4000;
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    include /etc/nginx/conf.d/*.conf;
}
